name: Codacy Coverage and Quality Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  codacy-quality-and-coverage:
    name: Codacy Coverage and Quality Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0"

      # Step 3: Run tests and generate coverage
      - name: Run tests and generate coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/tmp/coverage.opencover.xml

      # Step 4: Verify coverage file
      - name: Verify coverage file
        run: |
          if [ ! -f /tmp/coverage.opencover.xml ]; then
            echo "Coverage file not found!"
            exit 1
          else
            echo "Coverage file generated successfully."
          fi

      # Step 5: Upload coverage to Codacy
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r /tmp/coverage.opencover.xml

      # Step 6: Run Codacy Analysis CLI (Quality and Security)
      - name: Download the latest Codacy Analysis CLI
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/codacy/codacy-analysis-cli/releases/latest | jq -r '.assets[] | select(.name | contains("linux")) | .browser_download_url')
          wget $LATEST_URL -O codacy-analysis-cli
          chmod +x codacy-analysis-cli

      - name: Run Codacy Analysis CLI
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          ./codacy-analysis-cli analyze --project-token $CODACY_PROJECT_TOKEN --verbose
