name: Codacy Coverage and Quality Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  codacy-quality-and-coverage:
    name: Codacy Coverage and Quality Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0"

      # Step 3: Run tests and generate coverage
      - name: Run tests and generate coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/tmp/coverage.opencover.xml

      # Step 4: Verify coverage file
      - name: Verify coverage file
        run: |
          if [ ! -f /tmp/coverage.opencover.xml ]; then
            echo "Coverage file not found!"
            exit 1
          else
            echo "Coverage file generated successfully."
          fi

      # Step 5: Upload coverage to Codacy
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r /tmp/coverage.opencover.xml

      # Step 6: Run Codacy Analysis CLI (Quality and Security)
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
