name: Codacy Coverage and Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  codacy-security-coverage:
    name: Codacy Coverage and Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0"

      # Step 3: Clean and restore
      - name: Clean project
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Run tests and generate coverage
      - name: Run tests and generate coverage
        run: dotnet test TestPrueba/TestPrueba.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Shared.*]*" /p:CoverletOutput=/tmp/coverage.opencover.xml

      # Step 5: Verify coverage file
      - name: Verify coverage file
        run: |
          if [ ! -f /tmp/coverage.opencover.xml ]; then
            echo "Coverage file not found!"
            exit 1
          else
            echo "Coverage file generated successfully."
          fi

      # Step 6: Upload coverage to Codacy
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r /tmp/coverage.opencover.xml
