name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests with coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.opencover.xml
